version: "3.3"
services:
  switchboard:
    image: "switchboardlabs/node:${SBV2_ORACLE_VERSION:-dev-v2-5-3-22}" # https://hub.docker.com/r/switchboardlabs/node/tags
    network_mode: host
    restart: always
    environment:
      - LIVE=1
      - CLUSTER=${CLUSTER}
      - RPC_URL=${RPC_URL}
      - ORACLE_KEY=${ORACLE_KEY}
      - HEARTBEAT_INTERVAL=15
    volumes:
      - ./configs.json:/configs.json
secrets:
  PAYER_SECRETS:
    file: ${PAYER_SECRET_PATH}
