[programs.localnet]
anchor_vrf_parser = "25RhC9WBW4nV7ghS9r5tvqk4A5BRZTu22PhrKW1EmLyF"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "secrets/payer-keypair.json"
# cluster = "devnet"
# wallet = "secrets/payer-keypair.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.test.ts"
