name: Test deployment

on:
  pull_request:
    branches: [main]
    paths: [docs/**, ".github/workflows/*", "idl/**"]

jobs:
  test-deploy:
    name: Test deployment
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: docs
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: npm
          cache-dependency-path: "package-lock.json"
      - name: Setup npmrc
        run: echo "//registry.npmjs.org/:_authToken=${{secrets.NPM_AUTH_TOKEN}}" > .npmrc
      - name: Test build
        run: |
          npm ci
          npm run build:site
